name: Daily Stock Scraper

on:
  schedule:

    - cron: '0 18 * * 0-4'
  
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas psycopg2-binary python-dotenv yfinance

      - name: Run Fetch Prices
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python fetch_prices.py